name: Supabase-Mirror

on:
  schedule:
    - cron: '0 0 * * 5' # 每周五的0:00
  workflow_dispatch:

jobs:
  push_docker_folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clone supabase repository and prepare files
      run: |
        git clone --depth 1 https://github.com/supabase/supabase
        cd supabase/docker
        if [ -f .env.example ]; then
          cp .env.example .env
          echo ".env.example found and copied to .env"
        else
          echo ".env.example not found in supabase/docker"
          ls -la  # 列出目录内容以便调试
        fi

    - name: Push changes to mirror branch
      uses: ad-m/github-push-action@v0.8.0
      with:
        branch: mirror
        force: true
        directory: supabase/docker
