name: Supabase-Mirror

on:
  schedule:
    - cron: '0 0 * * 5' # 每周五的0:00
  workflow_dispatch:

jobs:
  push_docker_folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clone supabase repository and prepare files
      run: |
        git clone --depth 1 https://github.com/supabase/supabase
        cd supabase/docker
        if [ -f .env.example ]; then
          cp .env.example .env
          echo ".env.example found and copied to .env"
        else
          echo ".env.example not found in supabase/docker"
          ls -la  # 列出目录内容以便调试

    - name: Push docker folder to mirror branch
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: mirror
        build_dir: supabase/docker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
